[build]
  publish = "./"
  functions = "netlify/functions"

[dev]
  publish = "./"
  functions = "netlify/functions"
  port = 8888

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/dashboard"
  to = "/dashboard.html"
  status = 200

[[redirects]]
  from = "/style.css"
  to = "/public/style.css"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200